JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
		  ListNode.java \
		  Interval.java \
		  TreeNode.java \
		  RandomListNode.java \
		  Point.java \
		  MaxPointsOnALine.java \
		  LRUCache.java \
		  WordBreak.java \
		  CopyListWithRandomPointer.java \
		  Candy.java \
		  LongestConsecutiveSequence.java \
		  BestTimeToBuyAndSellStockIV.java \
		  BestTimeToBuyAndSellStockIII.java \
		  WordLadderII.java \
		  WordLadder.java \
		  ValidPalindrome.java \
		  InterleavingString.java \
		  ValidateBinarySearchTree.java \
		  UniqueBinarySearchTrees.java \
		  BinaryTreeInorderTraversal.java \
		  RestoreIpAddresses.java \
		  ReverseLinkedListII.java \
		  SubsetsII.java \
		  MergeSortedArray.java \
		  PartitionList.java \
		  LargestRectangleInHistogram.java \
		  RemoveDuplicatesFromSortedListII.java \
		  RemoveDuplicatesFromSortedList.java \
		  SearchInRotatedSortedArrayII.java \
		  RemoveDuplicatesFromSortedArrayII.java \
		  WordSearch.java \
		  Subsets.java \
		  Combinations.java \
		  MinimumWindowSubstring.java \
		  SortColors.java \
		  SearchA2DMatrix.java \
		  SetMatrixZeroes.java \
		  EditDistance.java \
		  SimplifyPath.java \
		  ClimbingStairs.java \
		  SqrtX.java \
		  TextJustification.java \
		  PlusOne.java \
		  ValidNumber.java \
		  AddBinary.java \
		  MergeTwoSortedLists.java \
		  MinimumPathSum.java \
		  UniquePaths.java \
		  UniquePathsII.java \
		  RotateList.java \
		  PermutationSequence.java \
		  SpiralMatrixII.java \
		  LengthOfLastWord.java \
		  InsertInterval.java \
		  MergeIntervals.java \
		  JumpGame.java \
		  SpiralMatrix.java \
		  NQueensII.java \
		  NQueens.java \
		  Pow.java \
		  Anagrams.java \
		  RotateImage.java \
		  PermutationsII.java \
		  Permutations.java \
		  JumpGameII.java \
		  WildcardMatching.java \
		  MultiplyStrings.java \
		  TrappingRainWater.java \
		  FirstMissingPositive.java \
		  CombinationSumII.java \
		  CombinationSum.java \
		  CountAndSay.java \
		  SudokuSolver.java \
		  ValidSudoku.java \
		  SearchInsertPosition.java \
		  SearchForARange.java \
		  SearchInRotatedSortedArray.java \
		  SubstringWithConcatenationOfAllWords.java \
		  LongestValidParentheses.java \
		  DivideTwoIntegers.java \
		  RemoveElement.java \
		  RemoveDuplicatesFromSortedArray.java \
		  ReverseNodesInKGroup.java \
		  SwapNodesInPairs.java \
		  MergeKSortedLists.java \
		  GenerateParentheses.java \
		  ValidParentheses.java \
		  RemoveNthNodeFromEndOfList.java \
		  LetterCombinationsOfAPhoneNumber.java \
		  FourSum.java \
		  ThreeSumClosest.java \
		  ThreeSum.java \
		  LongestCommonPrefix.java \
		  RomanToInteger.java \
		  IntegerToRoman.java \
		  ContainerWithMostWater.java \
		  RegularExpressionMatching.java \
		  PalindromeNumber.java \
		  StringToInteger.java \
		  ReverseInteger.java \
		  ZigZagConversion.java \
		  LongestPalindromicSubstring.java \
		  AddTwoNumbers.java \
		  LongestSubstringWithoutRepeatingCharacters.java \
		  MedianOfTwoSortedArrays.java \
		  TwoSum.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class
